name: CI
on: [push, pull_request]

jobs:
  build_test:
    name: Build and Test
    strategy:
      matrix:
        go: ['1.14']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.2
    - uses: actions/setup-go@v3.2.0
      with:
        go-version: ${{ matrix.go }}
        stable: false
    - name: Build and Test
      run: go test ./...
